// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxji3sXaqpkzZ6V53KhKD9UuenTilYk20',
    appId: '1:137656682466:web:fa9450ff5da355caa55bbb',
    messagingSenderId: '137656682466',
    projectId: 'cyberrent-c3ba2',
    authDomain: 'cyberrent-c3ba2.firebaseapp.com',
    storageBucket: 'cyberrent-c3ba2.firebasestorage.app',
    measurementId: 'G-9GHN5YFYQC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYCvaH3H3bYakQf_JYjchqmZCfpOrgREc',
    appId: '1:137656682466:android:8a55604c552f1d92a55bbb',
    messagingSenderId: '137656682466',
    projectId: 'cyberrent-c3ba2',
    storageBucket: 'cyberrent-c3ba2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8z5Pa-vw5_hyJ2oN-al_6NvzqjRiMsbk',
    appId: '1:137656682466:ios:aca696393f106921a55bbb',
    messagingSenderId: '137656682466',
    projectId: 'cyberrent-c3ba2',
    storageBucket: 'cyberrent-c3ba2.firebasestorage.app',
    iosBundleId: 'com.example.utsApb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8z5Pa-vw5_hyJ2oN-al_6NvzqjRiMsbk',
    appId: '1:137656682466:ios:aca696393f106921a55bbb',
    messagingSenderId: '137656682466',
    projectId: 'cyberrent-c3ba2',
    storageBucket: 'cyberrent-c3ba2.firebasestorage.app',
    iosBundleId: 'com.example.utsApb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxji3sXaqpkzZ6V53KhKD9UuenTilYk20',
    appId: '1:137656682466:web:4cc59b8d38b19771a55bbb',
    messagingSenderId: '137656682466',
    projectId: 'cyberrent-c3ba2',
    authDomain: 'cyberrent-c3ba2.firebaseapp.com',
    storageBucket: 'cyberrent-c3ba2.firebasestorage.app',
    measurementId: 'G-JXPRTZBQYT',
  );
}
